from mazzolino/ruby-install

env RUBY_TYPE ruby
env RUBY_VERSION 2.1.2

run ruby-install $RUBY_TYPE $RUBY_VERSION
env PATH /opt/rubies/$RUBY_TYPE-$RUBY_VERSION/bin:/opt/rubies/$RUBY_TYPE-$RUBY_VERSION/gems/bin:$PATH
